language: node_js
node_js: '10'
branches:
  only:
    - master
script:
  - npm run build
  - npm run webpack:production
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN
