// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var TermNode$ReactHooksTemplate = require("./TermNode.bs.js");

var t = /* Abstraction */Block.__(1, [
    "y",
    /* Application */Block.__(2, [
        /* Token */Block.__(0, ["x"]),
        /* Token */Block.__(0, ["y"])
      ])
  ]);

ReactDOMRe.renderToElementWithId(React.createElement(TermNode$ReactHooksTemplate.make, {
          term: t
        }), "index1");

exports.t = t;
/*  Not a pure module */
