// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var TermNode$ReactHooksTemplate = require("./TermNode.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(TermNode$ReactHooksTemplate.make, { }), "index1");

/*  Not a pure module */
