// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Terms$ReactHooksTemplate = require("./Terms.bs.js");

function TermNode(Props) {
  var term = Props.term;
  return React.createElement("div", undefined, Terms$ReactHooksTemplate.termsToString(term));
}

var make = TermNode;

exports.make = make;
/* react Not a pure module */
