// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function termsToString(t) {
  switch (t.tag | 0) {
    case 0 : 
        return t[0];
    case 1 : 
        return "(\\" + (t[0] + (" -> " + (termsToString(t[1]) + ")")));
    case 2 : 
        return "(" + (termsToString(t[0]) + (" " + (termsToString(t[1]) + ")")));
    
  }
}

exports.termsToString = termsToString;
/* No side effect */
